language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.build("SPTK"); Pkg.test("SPTK", coverage=true)'
after_success:
- julia -e 'cd(Pkg.dir("SPTK")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
